import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";

import "@/styles/globals.scss";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={clsx(inter.className, "bg-background")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark" // Dark Mode
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
